server:
  port: 8082
logging:
  file:
    name: D://logs/globle.log
  level:
    com:
      shaohao:
        mytask:
          mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.50.140:3306/wof?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: mima
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      oracle-pooled-prepared-statements: false
      pool:
        prepared-statement-cache-enabled: false
        prepared-statement-cache-query-size: 0
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai

  redis:
    host: localhost
    port: 6379
    database: 0

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
  rocketmq:
    name-server: localhost:9876
    producer:
      group: seckill-producer-group
xxl:
  job:
    admin:
      addresses: http://localhost:8088/xxl-job-admin
    executor:
      appname: seckill-executor
      ip: localhost
      port: 9999

